# -*- mode: python ; coding: utf-8 -*-
# Comic Sorter — PyInstaller spec
# Generated by build_dmg.py. Edit here if you need to add data files or hidden imports.

import os

block_cipher = None

# Data files bundled into the app (source, dest-folder-inside-bundle)
added_files = [
    ('rules.json',          '.'),
    ('config.example.json', '.'),
    ('icon.icns',           '.'),
    ('icon.png',            '.'),
]

a = Analysis(
    ['app.py'],
    pathex=[os.path.abspath('.')],
    binaries=[],
    datas=added_files,
    hiddenimports=[
        'customtkinter',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
        '_tkinter',
        'rarfile',
        'send2trash',
        'send2trash.plat_other',
        'send2trash.plat_osx',
        'xml.etree.ElementTree',
        'xml.dom.minidom',
        'zipfile',
        'concurrent.futures',
        'threading',
        'queue',
        'app_paths',
        'core',
        'inference',
        'metadata',
        'injector',
        'scanner',
        'utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Comic Sorter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,          # No terminal window
    disable_windowed_traceback=False,
    argv_emulation=True,    # Required for macOS .app drag-and-drop support
    target_arch=None,       # Match the current machine arch (arm64 on Apple Silicon)
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.icns',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Comic Sorter',
)

app = BUNDLE(
    coll,
    name='Comic Sorter.app',
    icon='icon.icns',
    bundle_identifier='com.gts.comicsorter',
    version='1.1.0',
    info_plist={
        'CFBundleName': 'Comic Sorter',
        'CFBundleDisplayName': 'Comic Sorter',
        'CFBundleShortVersionString': '1.1.0',
        'CFBundleVersion': '1.1.0',
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '11.0',
        'NSHumanReadableCopyright': 'Copyright 2025 gts1117',
        # Allow the app to open files dropped onto it from Finder
        'CFBundleDocumentTypes': [
            {
                'CFBundleTypeName': 'Comic Book Archive',
                'CFBundleTypeExtensions': ['cbz', 'cbr'],
                'CFBundleTypeRole': 'Viewer',
            }
        ],
    },
)
